### ISSUE TITLE
Allow https protocol when webserver is behind load balancer

### ISSUE THREAD

**Issue by cinqi** [getgrav/grav-plugin-cdn#9]
I have setup where Grav is running behind a load balancer and SSL is ended in LB. Communication between LB and webserver is HTTP. 

`if (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') {`

For this use case would it be possible to add configuration which enables to add https as protocol eventhough the webserver itself is not configured to be https?

**Comment by cinqi** [comment]
Forked plugin, made these changes:
https://github.com/cinqi/grav-plugin-cdn/commit/77066c08b4754c1e97739bc35b525a2a1f7a6cc7

This is now installed to my staging enviroment and it works. This provides now https eventhough webserver itself is not using HTTPS as SSL is terminated at load balancer.

**Comment by rhukster** [comment]
Please click the "create pull request" button to create a pull request from your forked copy and i'll get it merged in with develop and get a new release out.  Thanks!

**Comment by cinqi** [comment]
Being handled in https://github.com/getgrav/grav-plugin-cdn/pull/10

**Comment by rhukster** [comment]
merged, thanks!
